### ISSUE TITLE
Add Feedback Feature...

### ISSUE THREAD

**Issue by shounak-dev** [shounak-dev/My-Music#6]

**Comment by yagueto** [comment]
Hi! I would be interested in helping out with this issue. What are you looking for exactly?

**Comment by shounak-dev** [comment]
I have already make the Ui for feedback tab......just make sure that when user send a feedback from the app, the feedback will come to the admin,s mail.And if you want to change the ui design for feedback tab....then please create an another issue.....then I will assign it to you

**Comment by yagueto** [comment]
Hi, I've just been able to take a look at the issue. I've noticed there's already code in https://github.com/shounak-dev/My-Music/blob/729dfdb10daa13e71a30f0e552243feb5e2517ad/app/src/main/java/com/shounak/music_player/FeedbackActivity.kt#L23-L56

However, it seems like it doesn't work, at least in my android version, due to an issue with the java mail package. 

Nonetheless, I believe it might be easier to use an API such as [formsubmit](https://formsubmit.co/) which allows to send emails via an http request, without needing to register. In this way, there are no hardcoded values (as in https://github.com/shounak-dev/My-Music/blob/729dfdb10daa13e71a30f0e552243feb5e2517ad/app/src/main/java/com/shounak/music_player/FeedbackActivity.kt#L26) and there's no need for more dependencies

**Comment by shounak-dev** [comment]
Yes.....but the code is not working properly,that's why I create the issue

**Comment by yagueto** [comment]
I've been trying to implement this; however, it's a bit difficult to mail it to the admin as it would require either logging in with a mail (which is difficult due to security issues) or using an API (which tends to require payment). What if instead we created an issue here at github with every submission? I can create a github action with [this](https://github.com/marketplace/actions/open-new-github-issue)

**Comment by shounak-dev** [comment]
Ok
